version: "3"
services:
  computation:
    container_name: jupyter_container
    build: docker/jupyter
    volumes:
      - ./NBA/:/home/jovyan/work
    ports:
      - "7777:8888"
    env_file:
      - config/jupyter.env
  triple_storage:
    container_name: neo4j_container
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - config/neo4j.env
  relational_storage:
    container_name: postgres_container
    build: docker/postgres
    ports:
      - "5432:5432"
