version: "3"
services:
  jupyter:
    build: docker/jupyter
    ports:
      - "8888:8888"
    env_file:
      - config/neo4j.env
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - config/neo4j.env
